### ISSUE TITLE
Worth adding a visibile version number of the app? 

### ISSUE THREAD

**Issue by narion** [iebb/F1MSaveApp#5]
## Summary

Wondering if its worth adding in a visibile representation of the app version number to make upgrades and such easier to tell.

**Comment by iebb** [comment]
since this is only a browser shell, and almost all functionalities are in the web, I have configured this to have auto-updates to ensure a best experience using it. Maybe when there is a full-local version I would do so?

**Comment by narion** [comment]
Love the tool that sounds like a good idea. Didn't realise it had auto update in place already. Thanks!
